package repository

import (
	"errors"
	"go-barcode-webapp/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var (
	ErrRequirementJobNotFound     = errors.New("requirement job not found")
	ErrRequirementProductNotFound = errors.New("requirement product not found")
	ErrRequirementAlreadyExists   = errors.New("job product requirement already exists")
	ErrRequirementNotFound        = errors.New("job product requirement not found")
	ErrRequirementBelowPositions  = errors.New("quantity cannot be smaller than the product positions")
)

type RequirementRepository struct {
	db *Database
}

func NewRequirementRepository(db *Database) *RequirementRepository {
	return &RequirementRepository{db: db}
}

// SaveRequirements replaces the manually planned quantities while preserving
// quantities generated by commercial product positions.
func (r *RequirementRepository) SaveRequirements(jobID uint, reqs []models.JobProductRequirement) error {
	return r.db.DB.Transaction(func(tx *gorm.DB) error {
		return r.SaveRequirementsTx(tx, jobID, reqs)
	})
}

// SaveRequirementsTx is used by the job workflow so the header and material
// plan commit together. Existing IDs remain stable for warehouse consumers.
func (r *RequirementRepository) SaveRequirementsTx(tx *gorm.DB, jobID uint, reqs []models.JobProductRequirement) error {
	requested := make(map[uint]int, len(reqs))
	for _, req := range reqs {
		if req.ProductID == 0 || req.Quantity <= 0 {
			continue
		}
		requested[req.ProductID] += req.Quantity
	}
	var existing []models.JobProductRequirement
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("job_id = ?", jobID).Find(&existing).Error; err != nil {
		return err
	}
	for _, req := range existing {
		manual := requested[req.ProductID]
		delete(requested, req.ProductID)
		total := manual + req.PositionQuantity
		if total == 0 {
			if err := tx.Delete(&req).Error; err != nil {
				return err
			}
			continue
		}
		if err := tx.Model(&req).Updates(map[string]interface{}{"manual_quantity": manual, "quantity": total}).Error; err != nil {
			return err
		}
	}
	for productID, quantity := range requested {
		req := models.JobProductRequirement{JobID: jobID, ProductID: productID, Quantity: quantity, ManualQuantity: quantity}
		if err := tx.Create(&req).Error; err != nil {
			return err
		}
	}
	return nil
}

// ReconcilePositionRequirements updates only the portion contributed by
// product positions. Manually planned additional material remains untouched.
func (r *RequirementRepository) ReconcilePositionRequirements(tx *gorm.DB, jobID uint) error {
	var totals []struct {
		ProductID uint `gorm:"column:product_id"`
		Quantity  int  `gorm:"column:quantity"`
	}
	if err := tx.Raw(`SELECT product_id, SUM(GREATEST(1, ROUND(quantity)::integer)) AS quantity
		FROM job_positions WHERE job_id = ? AND position_type = 'product' AND product_id IS NOT NULL
		GROUP BY product_id`, jobID).Scan(&totals).Error; err != nil {
		return err
	}
	positions := make(map[uint]int, len(totals))
	for _, total := range totals {
		positions[total.ProductID] = total.Quantity
	}
	var existing []models.JobProductRequirement
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("job_id = ?", jobID).Find(&existing).Error; err != nil {
		return err
	}
	for _, req := range existing {
		positionQuantity := positions[req.ProductID]
		delete(positions, req.ProductID)
		total := req.ManualQuantity + positionQuantity
		if total == 0 {
			if err := tx.Delete(&req).Error; err != nil {
				return err
			}
			continue
		}
		if err := tx.Model(&req).Updates(map[string]interface{}{"position_quantity": positionQuantity, "quantity": total}).Error; err != nil {
			return err
		}
	}
	for productID, quantity := range positions {
		req := models.JobProductRequirement{JobID: jobID, ProductID: productID, Quantity: quantity, PositionQuantity: quantity}
		if err := tx.Create(&req).Error; err != nil {
			return err
		}
	}
	return nil
}

// CreateRequirement adds one new product requirement without modifying any
// existing requirement. This is the additive API used by guided integrations.
func (r *RequirementRepository) CreateRequirement(req *models.JobProductRequirement) error {
	return r.db.DB.Transaction(func(tx *gorm.DB) error {
		req.ManualQuantity = req.Quantity
		var jobCount int64
		if err := tx.Model(&models.Job{}).Where("jobid = ? AND deleted_at IS NULL", req.JobID).Count(&jobCount).Error; err != nil {
			return err
		}
		if jobCount == 0 {
			return ErrRequirementJobNotFound
		}

		var productCount int64
		if err := tx.Model(&models.Product{}).Where("productid = ? AND lifecycle_status = ?", req.ProductID, "active").Count(&productCount).Error; err != nil {
			return err
		}
		if productCount == 0 {
			return ErrRequirementProductNotFound
		}

		result := tx.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "job_id"}, {Name: "product_id"}},
			DoNothing: true,
		}).Create(req)
		if result.Error != nil {
			return result.Error
		}
		if result.RowsAffected == 0 {
			return ErrRequirementAlreadyExists
		}
		return nil
	})
}

// UpdateQuantity changes exactly one requirement belonging to the supplied job.
// It intentionally cannot change the linked job or product.
func (r *RequirementRepository) UpdateQuantity(jobID, requirementID uint, quantity int) (*models.JobProductRequirement, int, error) {
	var requirement models.JobProductRequirement
	oldQuantity := 0
	err := r.db.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("id = ? AND job_id = ?", requirementID, jobID).First(&requirement).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return ErrRequirementNotFound
			}
			return err
		}
		oldQuantity = requirement.Quantity
		if quantity < requirement.PositionQuantity {
			return ErrRequirementBelowPositions
		}
		if err := tx.Model(&requirement).Updates(map[string]interface{}{
			"quantity": quantity, "manual_quantity": quantity - requirement.PositionQuantity,
		}).Error; err != nil {
			return err
		}
		requirement.Quantity = quantity
		return tx.Preload("Product").First(&requirement, requirement.ID).Error
	})
	if err != nil {
		return nil, 0, err
	}
	return &requirement, oldQuantity, nil
}

// GetByJobID returns all requirements for a job, with product preloaded.
func (r *RequirementRepository) GetByJobID(jobID uint) ([]models.JobProductRequirement, error) {
	var reqs []models.JobProductRequirement
	err := r.db.Where("job_id = ?", jobID).
		Preload("Product").
		Order("id ASC").
		Find(&reqs).Error
	return reqs, err
}
