package repository

import (
	"errors"
	"go-barcode-webapp/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var (
	ErrRequirementJobNotFound     = errors.New("requirement job not found")
	ErrRequirementProductNotFound = errors.New("requirement product not found")
	ErrRequirementAlreadyExists   = errors.New("job product requirement already exists")
	ErrRequirementNotFound        = errors.New("job product requirement not found")
	ErrRequirementBelowPositions  = errors.New("quantity cannot be smaller than the product positions")
)

type RequirementRepository struct {
	db *Database
}

func NewRequirementRepository(db *Database) *RequirementRepository {
	return &RequirementRepository{db: db}
}

// SaveRequirements replaces the manually planned quantities while preserving
// quantities generated by commercial product positions.
func (r *RequirementRepository) SaveRequirements(jobID uint, reqs []models.JobProductRequirement) error {
	return r.db.DB.Transaction(func(tx *gorm.DB) error {
		return r.SaveRequirementsTx(tx, jobID, reqs)
	})
}

// SaveRequirementsTx is used by the job workflow so the header and material
// plan commit together. Existing IDs remain stable for warehouse consumers.
func requirementPositionTotals(tx *gorm.DB, jobID uint) (map[uint]int, error) {
	var totals []struct {
		ProductID uint `gorm:"column:product_id"`
		Quantity  int  `gorm:"column:quantity"`
	}
	if err := tx.Raw(`SELECT product_id,SUM(GREATEST(1,ROUND(quantity)::integer)) AS quantity
        FROM job_positions WHERE job_id=? AND position_type='product' AND COALESCE(to_jsonb(job_positions)->>'deleted_at','')='' AND product_id IS NOT NULL GROUP BY product_id`, jobID).Scan(&totals).Error; err != nil {
		return nil, err
	}
	result := map[uint]int{}
	for _, total := range totals {
		result[total.ProductID] = total.Quantity
	}
	return result, nil
}

// Restore the retained identity in a separate statement before changing values.
// Both statements remain in the caller's business transaction.
func restoreNativeRequirement(tx *gorm.DB, req *models.JobProductRequirement) error {
	if !req.DeletedAt.Valid {
		return nil
	}
	if err := tx.Unscoped().Model(req).Update("deleted_at", nil).Error; err != nil {
		return err
	}
	req.DeletedAt = gorm.DeletedAt{}
	return nil
}

func (r *RequirementRepository) SaveRequirementsTx(tx *gorm.DB, jobID uint, reqs []models.JobProductRequirement) error {
	requested := map[uint]int{}
	for _, req := range reqs {
		if req.ProductID > 0 && req.Quantity > 0 {
			requested[req.ProductID] += req.Quantity
		}
	}
	positions, err := requirementPositionTotals(tx, jobID)
	if err != nil {
		return err
	}
	var existing []models.JobProductRequirement
	if err = tx.Unscoped().Clauses(clause.Locking{Strength: "UPDATE"}).Where("job_id=?", jobID).Order("id").Find(&existing).Error; err != nil {
		return err
	}
	for _, req := range existing {
		manual := requested[req.ProductID]
		delete(requested, req.ProductID)
		position := positions[req.ProductID]
		total := manual + position
		if total == 0 {
			if !req.DeletedAt.Valid {
				if err = tx.Delete(&req).Error; err != nil {
					return err
				}
			}
			continue
		}
		if err = restoreNativeRequirement(tx, &req); err != nil {
			return err
		}
		if err = tx.Model(&req).Updates(map[string]any{"manual_quantity": manual, "position_quantity": position, "quantity": total}).Error; err != nil {
			return err
		}
	}
	for productID, manual := range requested {
		position := positions[productID]
		req := models.JobProductRequirement{JobID: jobID, ProductID: productID, Quantity: manual + position, ManualQuantity: manual, PositionQuantity: position}
		if err = tx.Create(&req).Error; err != nil {
			return err
		}
	}
	return nil
}

// ReconcilePositionRequirements updates only the portion contributed by
// product positions. Removing the last contribution archives the original row;
// later source/manual selection restores its stable identity in the same TX.
func (r *RequirementRepository) ReconcilePositionRequirements(tx *gorm.DB, jobID uint) error {
	return r.reconcilePositionRequirements(tx, jobID, 0, nil)
}

// ReconcileProductPositionRequirement limits a guided position change to its
// product and applies an explicitly reviewed manual replacement in the same update.
func (r *RequirementRepository) ReconcileProductPositionRequirement(tx *gorm.DB, jobID, productID uint, manualQuantity *int64) error {
	return r.reconcilePositionRequirements(tx, jobID, productID, manualQuantity)
}
func (r *RequirementRepository) reconcilePositionRequirements(tx *gorm.DB, jobID, productID uint, manualQuantity *int64) error {
	positions, err := requirementPositionTotals(tx, jobID)
	if err != nil {
		return err
	}
	if productID != 0 {
		for key := range positions {
			if key != productID {
				delete(positions, key)
			}
		}
	}
	var existing []models.JobProductRequirement
	query := tx.Unscoped()
	if productID != 0 {
		query = query.Where("product_id=?", productID)
	}
	if err = query.Clauses(clause.Locking{Strength: "UPDATE"}).Where("job_id=?", jobID).Order("id").Find(&existing).Error; err != nil {
		return err
	}
	for _, req := range existing {
		position := positions[req.ProductID]
		delete(positions, req.ProductID)
		manual := req.ManualQuantity
		if req.DeletedAt.Valid {
			if position == 0 {
				continue
			}
			// Restoring a source position does not revive manually removed demand.
			manual = 0
			if err = restoreNativeRequirement(tx, &req); err != nil {
				return err
			}
		}
		if manualQuantity != nil {
			manual = int(*manualQuantity)
		}
		total := manual + position
		if total == 0 {
			if err = tx.Delete(&req).Error; err != nil {
				return err
			}
			continue
		}
		if err = tx.Model(&req).Updates(map[string]any{"manual_quantity": manual, "position_quantity": position, "quantity": total}).Error; err != nil {
			return err
		}
	}
	for productID, position := range positions {
		manual := 0
		if manualQuantity != nil {
			manual = int(*manualQuantity)
		}
		req := models.JobProductRequirement{JobID: jobID, ProductID: productID, Quantity: manual + position, ManualQuantity: manual, PositionQuantity: position}
		if err = tx.Create(&req).Error; err != nil {
			return err
		}
	}
	return nil
}

// CreateRequirement adds one new product requirement without modifying any
// existing requirement. This is the additive API used by guided integrations.
func (r *RequirementRepository) CreateRequirement(req *models.JobProductRequirement) error {
	return r.db.DB.Transaction(func(tx *gorm.DB) error {
		req.ManualQuantity = req.Quantity
		var jobCount int64
		if err := tx.Model(&models.Job{}).Where("jobid = ? AND deleted_at IS NULL", req.JobID).Count(&jobCount).Error; err != nil {
			return err
		}
		if jobCount == 0 {
			return ErrRequirementJobNotFound
		}

		var productCount int64
		if err := tx.Model(&models.Product{}).Where("productid = ? AND lifecycle_status = ?", req.ProductID, "active").Count(&productCount).Error; err != nil {
			return err
		}
		if productCount == 0 {
			return ErrRequirementProductNotFound
		}

		result := tx.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "job_id"}, {Name: "product_id"}},
			DoNothing: true,
		}).Create(req)
		if result.Error != nil {
			return result.Error
		}
		if result.RowsAffected == 0 {
			return ErrRequirementAlreadyExists
		}
		return nil
	})
}

// UpdateQuantity changes exactly one requirement belonging to the supplied job.
// It intentionally cannot change the linked job or product.
func (r *RequirementRepository) UpdateQuantity(jobID, requirementID uint, quantity int) (*models.JobProductRequirement, int, error) {
	var requirement models.JobProductRequirement
	oldQuantity := 0
	err := r.db.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("id = ? AND job_id = ?", requirementID, jobID).First(&requirement).Error; err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return ErrRequirementNotFound
			}
			return err
		}
		oldQuantity = requirement.Quantity
		if quantity < requirement.PositionQuantity {
			return ErrRequirementBelowPositions
		}
		if err := tx.Model(&requirement).Updates(map[string]interface{}{
			"quantity": quantity, "manual_quantity": quantity - requirement.PositionQuantity,
		}).Error; err != nil {
			return err
		}
		requirement.Quantity = quantity
		return tx.Preload("Product").First(&requirement, requirement.ID).Error
	})
	if err != nil {
		return nil, 0, err
	}
	return &requirement, oldQuantity, nil
}

// GetByJobID returns all requirements for a job, with product preloaded.
func (r *RequirementRepository) GetByJobID(jobID uint) ([]models.JobProductRequirement, error) {
	var reqs []models.JobProductRequirement
	err := r.db.Where("job_id = ?", jobID).
		Preload("Product").
		Order("id ASC").
		Find(&reqs).Error
	return reqs, err
}
